id = "reasonml"
name = "reasonml"
description = "reasonml support."
version = "0.0.1"
repository = "https://github.com/jpx/tree-sitter-reason"

[grammars.reasonml]
repository = "https://github.com/jpx/tree-sitter-reason"
commit = "a26c84df01759c0dc24c4108f5f8bbf9eb91a1c1"
